### ISSUE TITLE
ADD: Offline signing

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#263]
# Offline signing

One device can be completely offline, only use QR codes to sign:

Step 1: use QR code to send tx data to co-device

Step 2: both devices do pre-processing on the keysign, return signed image

Step 3: one device shares image via QR code to other device

Step 4: Other device finishes and broadcasts

**Comment by johnnyluo** [comment]
This is not possible at the moment, if user are concerned , they can create a local wifi network , without internet access. 
But it can't sign without communications between the keysign parties.  Using QR code is not an option either.
1. QR code can hold not more than 4KB of data , some of the payload during keysign is larger than this
2. Even assume option 1 is not a problem ,  usability is a huge problem ,  because ECDSA keysign take 10 rounds , so user need to scan barcode back and forth for 20 times to sign one tx
