### ISSUE TITLE
Change from Chain Name to Chain TYPE

### ISSUE THREAD

**Issue by enriquesouza** [voltix-vault/voltix#306]
Every time we need to add a new chain or coin we have to change 19 files because we need to find all Switches that has this chain names. 

Instead we already have a chain type enum with contains UTXO, EVM, ... we can improve or rename it, but we must change it otherwise we will always need to change many files instead of only changing the TokenStore.

Ex:
```.ethereum, .avalanche, .bscChain, .arbitrum, .base, .optimism, .polygon, .blast, .cronosChain:```

**Comment by johnnyluo** [comment]
chain type is a weird property , like thorchain is not a chain type , thorchain is a cosmos chain , and also solana is not a chaintype  , it is a specific chain
 
currently chain is a enum , which make adding new chains easier , because complier can help us to identify the places easily

Let's continue to stick to chain , and avoid using chain type please.
